### ISSUE TITLE
Bundle OpenSSL

### ISSUE THREAD

**Issue by edjiang** [Zewo/COpenSSL#4]
As of 9 days ago:

https://github.com/Homebrew/brew/pull/597

```bash
> brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only OpenSSL means you may end up linking against the insecure,
deprecated system version while using the headers from the Homebrew version.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

It seems that Homebrew does not like `brew link openssl --force` anymore, and so Travis is failing any macOS builds using COpenSSL

https://github.com/dotnet/cli/issues/3964#issuecomment-236832511

Homebrew maintainer says the "right" solution is to bundle OpenSSL with the software.

**Comment by paulofaria** [comment]
> Homebrew maintainer says the "right" solution is to bundle OpenSSL with the software.
this would mean install open ssl in a custom location?
we can't compile open ssl with SwiftPM as of now

**Comment by edjiang** [comment]
I talked with Paulo on Slack about this --

https://github.com/IBM-Swift/CCurl-bin

IBM is distributing binaries in their CCurl library. We could potentially do this too, although this might be super unsafe. Paulo is going to look into this.

**Comment by paulofaria** [comment]
Solved!
